export const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  loginCard: {
    background: 'white',
    borderRadius: '24px',
    padding: '3rem',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.1)',
    width: '100%',
    maxWidth: '450px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '2rem',
  },
  titulo: {
    fontSize: '2rem',
    fontWeight: 800,
    background: 'linear-gradient(135deg, #2563eb, #1e40af)',
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
    marginBottom: '0.5rem',
    lineHeight: '1.2',
  },
  subtitulo: {
    fontSize: '1rem',
    color: '#64748b',
    fontWeight: 500,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  erroMessage: {
    background: '#fee2e2',
    color: '#dc2626',
    padding: '0.75rem 1rem',
    borderRadius: '12px',
    fontSize: '0.875rem',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #fecaca',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: '1rem',
    color: '#64748b',
    fontSize: '1.1rem',
    zIndex: 1,
  },
  input: {
    width: '100%',
    padding: '1rem 1rem 1rem 3rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    background: '#fafbfc',
  },
  togglePassword: {
    position: 'absolute',
    right: '1rem',
    background: 'none',
    border: 'none',
    color: '#64748b',
    cursor: 'pointer',
    padding: '0.5rem',
    borderRadius: '8px',
    transition: 'all 0.2s',
  },
  options: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.875rem',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#64748b',
    cursor: 'pointer',
  },
  checkbox: {
    cursor: 'pointer',
  },
  forgotPassword: {
    color: '#2563eb',
    textDecoration: 'none',
    fontWeight: 500,
    transition: 'color 0.2s',
  },
  submitButton: {
    padding: '1rem',
    background: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    margin: '2rem 0',
    position: 'relative',
    justifyContent: 'center',
  },
  dividerText: {
    background: 'white',
    padding: '0 1rem',
    color: '#64748b',
    fontSize: '0.875rem',
    fontWeight: 500,
    position: 'relative',
    zIndex: 1,
  },
  socialLogin: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  socialButton: {
    padding: '0.875rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    background: 'white',
    fontSize: '0.9rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.3s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  signup: {
    textAlign: 'center',
    marginTop: '2rem',
  },
  signupText: {
    fontSize: '0.875rem',
    color: '#64748b',
  },
  signupLink: {
    color: '#2563eb',
    textDecoration: 'none',
    fontWeight: 600,
    transition: 'color 0.2s',
  },
  backButton: {
    position: 'absolute',
    top: '2rem',
    left: '2rem',
    width: '48px',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#2563eb',
    textDecoration: 'none',
    borderRadius: '50%',
    fontSize: '1.2rem',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    ':hover': {
      background: 'rgba(255, 255, 255, 1)',
      color: '#1d4ed8',
      transform: 'translateX(-2px) scale(1.1)',
      boxShadow: '0 6px 16px rgba(0, 0, 0, 0.15)',
    },
  },
};
