export const styles = {
  wrapper: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2rem',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  card: {
    background: 'white',
    borderRadius: '12px',
    boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
    width: '100%',
    maxWidth: '500px',
    padding: '2rem',
  },
  logo: {
    textAlign: 'center' as const,
    fontSize: '2rem',
    fontWeight: 800,
    background: 'linear-gradient(135deg, #4361ee, #7209b7)',
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
    marginBottom: '0.5rem',
  },
  subtitle: {
    textAlign: 'center' as const,
    color: '#6c757d',
    marginBottom: '2rem',
    fontSize: '0.9rem',
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  label: {
    display: 'block',
    fontWeight: 600,
    marginBottom: '0.5rem',
    color: '#2c3e50',
    fontSize: '0.9rem',
  },
  radioGroup: {
    display: 'flex',
    gap: '1rem',
    marginTop: '0.5rem',
  },
  radioOption: (isActive: boolean) => ({
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    border: `2px solid ${isActive ? '#4361ee' : '#e9ecef'}`,
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    backgroundColor: isActive ? 'rgba(67, 97, 238, 0.05)' : 'transparent',
  }),
  inputWrapper: {
    position: 'relative' as const,
  },
  inputIcon: {
    position: 'absolute' as const,
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#6c757d',
  },
  input: (hasError: boolean) => ({
    width: '100%',
    padding: '10px 12px 10px 40px',
    border: `2px solid ${hasError ? '#ef476f' : '#e9ecef'}`,
    borderRadius: '8px',
    fontSize: '1rem',
    transition: 'all 0.3s',
    fontFamily: 'inherit',
    outline: 'none',
    ':focus': {
      borderColor: '#4361ee',
    },
  }),
  errorText: {
    color: '#ef476f',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
    display: 'block',
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  },
  checkboxLabel: {
    fontSize: '0.9rem',
  },
  link: {
    color: '#4361ee',
    textDecoration: 'none',
    fontWeight: 600,
    transition: 'color 0.2s',
  },
  backButton: {
    position: 'absolute' as const,
    top: '2rem',
    left: '2rem',
    width: '48px',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#2563eb',
    textDecoration: 'none',
    borderRadius: '50%',
    fontSize: '1.2rem',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
  } as React.CSSProperties,
  button: {
    width: '100%',
    padding: '12px',
    background: 'linear-gradient(135deg, #4361ee, #7209b7)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'transform 0.2s',
    ':hover': {
      transform: 'translateY(-2px)',
    },
  },
  buttonDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
    transform: 'none',
  },
  loginRedirect: {
    textAlign: 'center' as const,
    marginTop: '1.5rem',
    fontSize: '0.9rem',
  },
  optional: {
    fontSize: '0.8rem',
    fontWeight: 'normal',
    color: '#6c757d',
  },
  generalError: {
    background: '#ffe5e5',
    color: '#ef476f',
    padding: '10px',
    borderRadius: '8px',
    marginBottom: '1rem',
    textAlign: 'center' as const,
    fontSize: '0.9rem',
  },
  successMessage: {
    background: '#e5f5e5',
    color: '#06d6a0',
    padding: '10px',
    borderRadius: '8px',
    marginBottom: '1rem',
    textAlign: 'center' as const,
    fontSize: '0.9rem',
  },
  '@media (max-width: 640px)': {
    card: {
      padding: '1.5rem',
    },
    radioGroup: {
      flexDirection: 'column',
    },
    wrapper: {
      padding: '1rem',
    },
  },
};