export const cardStyles = {
  card: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer',
    border: '1px solid #f1f5f9',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'start',
    marginBottom: '1rem',
    paddingBottom: '1rem',
    borderBottom: '1px solid #e9ecef',
  },
  motoristaInfo: {
    flex: 1,
  },
  motoristaNome: {
    fontSize: '1.2rem',
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: '0.25rem',
    lineHeight: '1.3',
  },
  universidade: {
    fontSize: '0.875rem',
    color: '#64748b',
    marginBottom: '0.5rem',
    fontWeight: 500,
  },
  avaliacao: {
    display: 'flex',
    gap: '2px',
    alignItems: 'center',
  },
  avaliacaoTexto: {
    fontSize: '0.8rem',
    color: '#64748b',
    marginLeft: '0.5rem',
    fontWeight: 500,
  },
  vagasBadge: {
    background: 'linear-gradient(135deg, #dcfce7, #bbf7d0)',
    color: '#166534',
    padding: '0.375rem 0.875rem',
    borderRadius: '24px',
    fontSize: '0.8rem',
    fontWeight: 600,
    border: '1px solid #86efac',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.25rem',
  },
  iconStyle: {
    width: '20px',
    color: '#2563eb',
    fontSize: '1rem',
  },
  rota: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  rotaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  linhaDivisor: {
    marginLeft: '10px',
    width: '2px',
    height: '15px',
    background: '#dee2e6',
  },
  dataHora: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1rem',
    padding: '1rem',
    background: 'linear-gradient(135deg, #f8fafc, #f1f5f9)',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
  },
  observacoes: {
    marginBottom: '1rem',
    fontSize: '0.875rem',
    color: '#64748b',
    padding: '0.75rem',
    background: '#fafbfc',
    borderRadius: '8px',
    borderLeft: '3px solid #2563eb',
  },
  precoVagas: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
    paddingTop: '0.5rem',
    borderTop: '1px solid #e9ecef',
  },
  preco: {
    fontSize: '1.5rem',
    fontWeight: 800,
    background: 'linear-gradient(135deg, #166534, #15803d)',
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
  },
  vagasRestantes: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#1e293b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#f8fafc',
    borderRadius: '8px',
    padding: '0.25rem 0.5rem',
    minWidth: '40px',
    height: '40px',
  },
  button: {
    width: '100%',
    padding: '0.875rem',
    background: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 2px 8px rgba(37, 99, 235, 0.25)',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  estrelaCheia: {
    color: '#ffc107',
    fontSize: '12px',
  },
  estrelaVazia: {
    color: '#ffc107',
    fontSize: '12px',
  },
};