// styles.ts - Estilos aprimorados para página de perfil com a paleta de cores do site
export const styles = {
  wrapper: {
    minHeight: '100vh',
    background: '#f5f6fa',
    padding: '2rem',
  },
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    position: 'relative' as const,
  },
  backButton: {
    position: 'fixed' as const,
    top: '2rem',
    left: '2rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.25rem',
    background: 'white',
    color: '#2563eb',
    textDecoration: 'none',
    borderRadius: '12px',
    fontSize: '0.9rem',
    fontWeight: 600,
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
    zIndex: 1000,
    ':hover': {
      background: '#f1f5f9',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
  } as React.CSSProperties,
  profileHeader: {
    background: 'white',
    borderRadius: '20px',
    padding: '2.5rem',
    marginBottom: '2rem',
    boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
    display: 'flex',
    gap: '2.5rem',
    flexWrap: 'wrap' as const,
    border: '1px solid #e5e7eb',
  },
  avatarWrapper: {
    position: 'relative' as const,
    flexShrink: 0,
  },
  avatar: {
    width: '130px',
    height: '130px',
    borderRadius: '24px',
    objectFit: 'cover' as const,
    border: '4px solid #f3f4f6',
  },
  avatarPlaceholder: {
    width: '130px',
    height: '130px',
    borderRadius: '24px',
    background: 'linear-gradient(135deg, #2563eb 0%, #4f46e5 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    border: '4px solid #f3f4f6',
  },
  changePhotoBtn: {
    position: 'absolute' as const,
    bottom: '-8px',
    right: '-8px',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: '#2563eb',
    border: '3px solid white',
    color: 'white',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
    ':hover': {
      transform: 'scale(1.1)',
      background: '#1d4ed8',
    },
  } as React.CSSProperties,
  profileInfo: {
    flex: 1,
    minWidth: '250px',
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    flexWrap: 'wrap' as const,
    marginBottom: '1rem',
  },
  name: {
    fontSize: '2.25rem',
    fontWeight: 800,
    color: '#1e293b',
    margin: 0,
    lineHeight: 1.1,
  },
  editButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1.125rem',
    background: '#f1f5f9',
    border: 'none',
    borderRadius: '10px',
    color: '#475569',
    fontSize: '0.875rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    ':hover': {
      background: '#e2e8f0',
      color: '#2563eb',
    },
  } as React.CSSProperties,
  badgeGroup: {
    display: 'flex',
    gap: '0.875rem',
    marginBottom: '1.25rem',
    flexWrap: 'wrap' as const,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    borderRadius: '100px',
    fontSize: '0.875rem',
    fontWeight: 600,
    background: '#f1f5f9',
    color: '#334155',
  },
  ratingWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '1.25rem',
    flexWrap: 'wrap' as const,
  },
  ratingValue: {
    fontWeight: 800,
    fontSize: '1.5rem',
    color: '#f59e0b',
  },
  ratingCount: {
    fontSize: '0.875rem',
    color: '#64748b',
  },
  bio: {
    fontSize: '0.9375rem',
    color: '#475569',
    lineHeight: 1.7,
    marginTop: '0.75rem',
  },
  editForm: {
    width: '100%',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1.25rem',
    marginBottom: '1.25rem',
  },
  formField: {
    marginBottom: '1.25rem',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: 700,
    marginBottom: '0.5rem',
    color: '#334155',
    letterSpacing: '-0.2px',
  },
  formInput: {
    width: '100%',
    padding: '0.875rem 1rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '0.9375rem',
    outline: 'none',
    transition: 'all 0.2s',
    fontFamily: 'inherit',
    ':focus': {
      borderColor: '#2563eb',
      boxShadow: '0 0 0 4px rgba(37, 99, 235, 0.1)',
      background: '#fafbff',
    },
  } as React.CSSProperties,
  formTextarea: {
    width: '100%',
    padding: '0.875rem 1rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '0.9375rem',
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    minHeight: '100px',
    ':focus': {
      borderColor: '#2563eb',
      boxShadow: '0 0 0 4px rgba(37, 99, 235, 0.1)',
      background: '#fafbff',
    },
  } as React.CSSProperties,
  editActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  saveButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.875rem 1.75rem',
    background: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '0.9375rem',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
    ':hover': {
      background: '#1d4ed8',
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 16px rgba(37, 99, 235, 0.4)',
    },
  } as React.CSSProperties,
  cancelButton: {
    padding: '0.875rem 1.75rem',
    background: '#f1f5f9',
    color: '#475569',
    border: 'none',
    borderRadius: '12px',
    fontSize: '0.9375rem',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s',
    ':hover': {
      background: '#e2e8f0',
      color: '#334155',
    },
  } as React.CSSProperties,
  tabsContainer: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    background: 'white',
    padding: '0.5rem',
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    border: '1px solid #e5e7eb',
  },
  tabButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.625rem',
    padding: '0.875rem 1.25rem',
    background: 'transparent',
    border: 'none',
    borderRadius: '12px',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  tabButtonActive: {
    background: '#2563eb',
    color: 'white',
    boxShadow: '0 2px 8px rgba(37, 99, 235, 0.25)',
  },
  tabContent: {
    minHeight: '400px',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '1.25rem',
  },
  infoCard: {
    display: 'flex',
    gap: '1.25rem',
    padding: '1.5rem',
    background: 'white',
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    border: '1px solid #e5e7eb',
    transition: 'all 0.2s',
    ':hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
    },
  } as React.CSSProperties,
  infoIcon: {
    width: '52px',
    height: '52px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)',
    borderRadius: '14px',
    color: '#2563eb',
    fontSize: '1.5rem',
    flexShrink: 0,
  },
  infoContent: {
    flex: 1,
    label: {
      fontSize: '0.75rem',
      fontWeight: 700,
      textTransform: 'uppercase' as const,
      color: '#94a3b8',
      letterSpacing: '0.8px',
      marginBottom: '0.25rem',
      display: 'block',
    },
    p: {
      fontSize: '1rem',
      color: '#1e293b',
      marginTop: '0.25rem',
      fontWeight: 500,
    },
  },
  changePasswordBtn: {
    marginTop: '0.75rem',
    padding: 0,
    background: 'none',
    border: 'none',
    color: '#2563eb',
    fontSize: '0.8125rem',
    fontWeight: 600,
    cursor: 'pointer',
    ':hover': {
      textDecoration: 'underline',
    },
  } as React.CSSProperties,
  historicoContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  historicoCard: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    transition: 'all 0.2s',
    border: '1px solid #e5e7eb',
    ':hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(0,0,0,0.08)',
    },
  } as React.CSSProperties,
  historicoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    background: '#f8fafc',
    borderBottom: '1px solid #e2e8f0',
  },
  historicoType: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.375rem 0.875rem',
    borderRadius: '8px',
    fontSize: '0.8125rem',
    fontWeight: 700,
  },
  historicoStatus: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    fontSize: '0.8125rem',
    fontWeight: 600,
  },
  historicoBody: {
    padding: '1.5rem',
  },
  historicoRoute: {
    marginBottom: '1rem',
  },
  routePoint: {
    display: 'flex',
    gap: '0.875rem',
    alignItems: 'flex-start',
  },
  routeDotOrigin: {
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    background: '#22c55e',
    marginTop: '4px',
    flexShrink: 0,
  },
  routeDotDestiny: {
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    background: '#ef4444',
    marginTop: '4px',
    flexShrink: 0,
  },
  routeLine: {
    width: '2px',
    height: '28px',
    background: '#e2e8f0',
    marginLeft: '6px',
  },
  routeLabel: {
    fontSize: '0.75rem',
    color: '#94a3b8',
    fontWeight: 600,
  },
  routeText: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#1e293b',
    marginTop: '2px',
  },
  historicoDetails: {
    display: 'flex',
    gap: '1.75rem',
    flexWrap: 'wrap' as const,
    padding: '1rem 0',
    borderTop: '1px solid #f1f5f9',
    borderBottom: '1px solid #f1f5f9',
    marginBottom: '1rem',
    '& > div': {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      fontSize: '0.9375rem',
      color: '#475569',
      fontWeight: 500,
    },
  },
  historicoMotorista: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.9375rem',
    color: '#64748b',
    marginBottom: '0.75rem',
    fontWeight: 500,
  },
  historicoVagas: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.9375rem',
    color: '#64748b',
    fontWeight: 500,
  },
  historicoButton: {
    width: '100%',
    padding: '0.875rem',
    background: '#f8fafc',
    border: 'none',
    borderTop: '1px solid #e2e8f0',
    color: '#2563eb',
    fontSize: '0.9375rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    ':hover': {
      background: '#f1f5f9',
      color: '#1d4ed8',
    },
  } as React.CSSProperties,
  verMaisButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.875rem',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    color: '#475569',
    fontSize: '0.9375rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    ':hover': {
      borderColor: '#2563eb',
      color: '#2563eb',
      background: '#f8fafc',
    },
  } as React.CSSProperties,
  avaliacoesContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  avaliacoesSummary: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: '2.5rem',
    padding: '2rem',
    background: 'white',
    borderRadius: '20px',
    alignItems: 'center',
    border: '1px solid #e5e7eb',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
  },
  summaryScore: {
    textAlign: 'center' as const,
    paddingRight: '2.5rem',
    borderRight: '2px solid #f1f5f9',
  },
  summaryScoreNumber: {
    fontSize: '3.5rem',
    fontWeight: 900,
    color: '#f59e0b',
    lineHeight: 1,
  },
  summaryStars: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.25rem',
    marginTop: '0.75rem',
  },
  summaryTotal: {
    fontSize: '0.875rem',
    color: '#64748b',
    marginTop: '0.5rem',
    fontWeight: 500,
  },
  summaryBreakdown: {
    flex: 1,
  },
  breakdownRow: {
    display: 'grid',
    gridTemplateColumns: '80px 1fr 40px',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '0.75rem',
    fontSize: '0.875rem',
  },
  breakdownBar: {
    height: '10px',
    background: '#f1f5f9',
    borderRadius: '100px',
    overflow: 'hidden',
  },
  breakdownFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #f59e0b 0%, #fbbf24 100%)',
    borderRadius: '100px',
    transition: 'width 0.5s ease',
  },
  avaliacoesList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  avaliacaoCard: {
    padding: '1.5rem',
    background: 'white',
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    border: '1px solid #e5e7eb',
    transition: 'all 0.2s',
    ':hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
    },
  } as React.CSSProperties,
  avaliacaoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1rem',
  },
  avaliacaoAutor: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  avaliacaoAvatar: {
    width: '48px',
    height: '48px',
    borderRadius: '14px',
    background: 'linear-gradient(135deg, #2563eb 0%, #4f46e5 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 700,
    fontSize: '1.125rem',
  },
  avaliacaoStars: {
    display: 'flex',
    gap: '0.125rem',
    marginTop: '0.375rem',
  },
  avaliacaoData: {
    fontSize: '0.8125rem',
    color: '#94a3b8',
    fontWeight: 500,
  },
  avaliacaoComentario: {
    fontSize: '0.9375rem',
    color: '#475569',
    lineHeight: 1.7,
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '4rem 2rem',
    background: 'white',
    borderRadius: '20px',
    color: '#64748b',
    border: '2px dashed #e2e8f0',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    backdropFilter: 'blur(4px)',
  },
  modalContent: {
    background: 'white',
    borderRadius: '20px',
    padding: '2.5rem',
    textAlign: 'center' as const,
    maxWidth: '420px',
    width: '90%',
    boxShadow: '0 25px 50px rgba(0,0,0,0.25)',
  },
  modalIcon: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1.25rem',
  },
  modalTitle: {
    fontSize: '1.375rem',
    fontWeight: 800,
    marginBottom: '0.5rem',
    color: '#1e293b',
  },
  modalMessage: {
    fontSize: '0.9375rem',
    color: '#64748b',
    lineHeight: 1.6,
  },

  // Media Queries Responsivas
  '@media (max-width: 768px)': {
    wrapper: {
      padding: '1rem',
    },
    profileHeader: {
      flexDirection: 'column' as const,
      alignItems: 'center',
      textAlign: 'center' as const,
      padding: '1.75rem',
    },
    nameRow: {
      justifyContent: 'center',
    },
    badgeGroup: {
      justifyContent: 'center',
    },
    ratingWrapper: {
      justifyContent: 'center',
    },
    formRow: {
      gridTemplateColumns: '1fr',
    },
    infoGrid: {
      gridTemplateColumns: '1fr',
    },
    avaliacoesSummary: {
      gridTemplateColumns: '1fr',
      textAlign: 'center' as const,
      gap: '1.5rem',
    },
    summaryScore: {
      borderRight: 'none',
      borderBottom: '2px solid #f1f5f9',
      paddingRight: 0,
      paddingBottom: '1.5rem',
    },
    tabsContainer: {
      flexDirection: 'column' as const,
    },
    backButton: {
      top: '1rem',
      left: '1rem',
      padding: '0.625rem 1rem',
    },
  },
};
